import { db } from './index';
import { categories, prompts } from './schema';
import { sql } from 'drizzle-orm';

const SEED_CATEGORIES = [
    { name: 'My Prompts', color: 'bg-yellow-100 text-yellow-700' },
    { name: 'Brainstorming', color: 'bg-pink-100 text-pink-700' },
    { name: 'Marketing', color: 'bg-blue-100 text-blue-700' },
    { name: 'Coding', color: 'bg-green-100 text-green-700' },
    { name: 'Nano Banana Pro', color: 'bg-purple-100 text-purple-700' },
];

const SEED_PROMPTS = [
    {
        title: 'Modern Facade Update',
        content: 'Using this render of a contemporary facade, replace the facade material with weathered corten steel and integrate subtle vertical louvers of natural wood. Maintain the original lighting and perspective.',
        categoryName: 'Nano Banana Pro',
    },
    {
        title: 'Daytime to Sunset',
        content: 'Using this daytime render of a building exterior, turn it into a sunset scene, add a few clouds to the sky, and incorporate warm artificial light spilling from the windows. Maintain the original building geometry.',
        categoryName: 'Nano Banana Pro',
    },
    {
        title: 'Blueprint to 3D Render',
        content: 'Transform this blueprint image into a photorealistic 3D rendering of a contemporary high-rise building with a glass facade, showing realistic reflections and ambient city lighting at dusk.',
        categoryName: 'Nano Banana Pro',
    },
    {
        title: 'Interior Morning Light',
        content: 'Transform this interior shot to show the space under soft, diffused morning light, with subtle volumetric fog filtering through the windows.',
        categoryName: 'Nano Banana Pro',
    },
    {
        title: 'Adding Vegetation',
        content: 'From this base image of a residential building, emphasize the intricate brickwork details and add climbing ivy to one side of the facade. Add two minimalist concrete planters with tall green foliage near the entrance.',
        categoryName: 'Nano Banana Pro',
    },
    {
        title: 'Style Transfer: Brutalist',
        content: "Using this photograph of a historic building, reimagine it as a brutalist architecture concept, maintaining the original building's massing but using raw concrete finishes and repetitive modular elements.",
        categoryName: 'Nano Banana Pro',
    },
    {
        title: 'Golden Hour Exterior',
        content: 'Modern sustainable office building exterior, featuring vertical gardens and solar panels, photographed from street level looking up, golden hour lighting with warm sunset glow, blue hour sky beginning to show, architectural photography style, sharp focus with high detail.',
        categoryName: 'Nano Banana Pro',
    },
];

async function seed() {
    console.log('Starting database seeding...');

    // Step 1: Clear existing data (prompts first due to FK constraint)
    console.log('Clearing existing data...');
    await db.delete(prompts);
    await db.delete(categories);
    console.log('✓ Cleared existing data');

    // Step 2: Insert categories (UUIDs auto-generated by the database)
    console.log('Seeding categories...');
    const insertedCategories = await db.insert(categories)
        .values(SEED_CATEGORIES.map(c => ({ name: c.name, color: c.color })))
        .returning();
    console.log(`✓ Inserted ${insertedCategories.length} categories`);

    // Step 3: Build a name→id map for linking prompts to categories
    const categoryMap = new Map(insertedCategories.map(c => [c.name, c.id]));

    // Step 4: Insert prompts with correct category UUIDs
    console.log('Seeding prompts...');
    const insertedPrompts = await db.insert(prompts)
        .values(SEED_PROMPTS.map(p => ({
            title: p.title,
            content: p.content,
            categoryId: categoryMap.get(p.categoryName) ?? null,
        })))
        .returning();
    console.log(`✓ Inserted ${insertedPrompts.length} prompts`);

    console.log('✓ Database seeding completed successfully!');

    // Print summary
    console.log('\nSummary:');
    for (const cat of insertedCategories) {
        const count = insertedPrompts.filter(p => p.categoryId === cat.id).length;
        console.log(`  ${cat.name} (${cat.id}): ${count} prompts`);
    }
}

seed().catch((err) => {
    console.error('Seeding failed:', err);
    process.exit(1);
});
